### PR TITLE
Display version 1.18

### PR DESCRIPTION
**Pull request by JoakimThorsen**
Title. #276 #277 #278 #279 #282 #288 #295

### CODE REVIEW

**Comment by wagyourtail** [comment]
duplicate, #276 #277 #278 #279 #282 #288 #295

**Comment by wagyourtail** [comment]
oops thought this was issues tab

**Comment by haykam821** [comment]
This might as well include 1.18 since the release candidates seem to work just fine with this.

**Comment by JoakimThorsen** [comment]
I mean, sure, I just figured it's technically unreleased still

**Comment by Earthcomputer** [comment]
Superseded by simply specifying latest

**Pull request closed without merging**
